language: go

go:
 - 1.8.x

env:
 DOCKER_COMPOSE_VERSION: 1.17.0-rc1

before_install:
 - sudo apt-get update
 - sudo apt-get install docker
 - sudo apt-get install docker.io
 - sudo apt-get install docker-compose

 - docker-compose pull
 - docker-compose build
 - docker-compose start

 - docker ps

after_install: