version: '3'
services:
  search:
    build:
      context: .
      dockerfile: searching.Dockerfile
    ports:
      - "50111:8080"
    networks:
      kitler:
        aliases:
          - searching
    environment:
      DWNLD: 'downloading:8080'
  download:
    image: down_image
    build:
      context: .
      dockerfile: loading.Dockerfile
    ports:
      - "50112:8080"
    networks:
      kitler:
        aliases:
          - downloading
networks:
  kitler: