version: '3'
services:
  search:
    build:
      context: .
      dockerfile: searching.Dockerfile
    ports:
      - "50111:50111"
    environment:
      DWNLD: '172.18.0.1:50112'
  download:
    build:
      context: .
      dockerfile: loading.Dockerfile
    ports:
      - "50112:50112"